using System;
using System.Drawing;
using System.Windows.Forms;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Lib;

namespace as5
{
    /// <summary>
    /// EnrolledStudentsForm
    /// </summary>
    internal class EnrolledStudentsForm : Form
    {
        /// <summary>
        /// fields
        /// </summary>
        private DataGridView _Grid;
        private University _University;
        /// <summary>
        /// Ctor
        /// </summary>
        /// <param name="u"></param>
        public EnrolledStudentsForm(University u)
        {
            this.InitializeComponent();
            _University = u;
            this.SetupGrid();
        }
        /// <summary>
        /// init grid
        /// </summary>
        private void SetupGrid()
        {
            var titles = new string[] { "Id", "Name", "Birth", "Address" };
            foreach (var t in titles)
                this._Grid.Columns.Add(t, t);
        }
        /// <summary>
        /// init, generated by vs
        /// </summary>
        private void InitializeComponent()
        {
            this._Grid = new System.Windows.Forms.DataGridView();
            ((System.ComponentModel.ISupportInitialize)(this._Grid)).BeginInit();
            this.SuspendLayout();
            // 
            // grid
            // 
            this._Grid.AllowUserToAddRows = false;
            this._Grid.AllowUserToDeleteRows = false;
            this._Grid.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this._Grid.AutoSizeRowsMode = System.Windows.Forms.DataGridViewAutoSizeRowsMode.AllHeaders;
            this._Grid.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this._Grid.Dock = System.Windows.Forms.DockStyle.Fill;
            this._Grid.Location = new System.Drawing.Point(0, 0);
            this._Grid.Name = "grid";
            this._Grid.ReadOnly = true;
            this._Grid.RowTemplate.Height = 23;
            this._Grid.Size = new System.Drawing.Size(595, 262);
            this._Grid.TabIndex = 0;
            // 
            // EnrolledStudentsForm
            // 
            this.ClientSize = new System.Drawing.Size(595, 262);
            this.Controls.Add(this._Grid);
            this.Name = "EnrolledStudentsForm";
            ((System.ComponentModel.ISupportInitialize)(this._Grid)).EndInit();
            this.ResumeLayout(false);
        }
        /// <summary>
        /// populate grid
        /// </summary>
        /// <param name="paperCode"></param>
        internal void PopulateGrid(int paperCode)
        {
            this._Grid.Rows.Clear();
            this._Grid.Refresh();
            var students = _University.FindEnrolledByPaper(paperCode);
            foreach (var s in students)
                this._Grid.Rows.Add(new string[] { s.Id.ToString(), s.Name, s.BirthDate.ToString(), s.Address });

            var paper = _University.FindPaper(paperCode);
            this.Text = "students enrolled in " + paper.Name + " " + paper.Number;
        }
    }
}
