using System;
using System.Drawing;
using System.Windows.Forms;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace as5
{
    /// <summary>
    /// abstraction for paper list to choose
    /// </summary>
    internal class PapersList : Form
    {
        /// <summary>
        /// papers list in a ListBox
        /// </summary>
        internal ListBox _List;
        public PapersList()
        {
            this.InitializeComponent();
            _List.MouseDoubleClick += delegate { this.Hide(); };
        }
        /// <summary>
        /// get selected paper code
        /// </summary>
        /// <returns>nullable int</returns>
        internal int? GetSelectedPaperCode()
        {
            if (_List.SelectedItem != null)
                return Convert.ToInt32(_List.GetItemText(_List.SelectedItem));
            else
                return null;
        }
        /// <summary>
        /// populate
        /// </summary>
        /// <param name="papers"></param>
        internal void Populate(string[] papers)
        {
            _List.Items.Clear();
            _List.Items.AddRange(papers);
            _List.ClearSelected();
        }
        /// <summary>
        /// generated by vs
        /// </summary>
        private void InitializeComponent()
        {
            _List = new System.Windows.Forms.ListBox();
            this.SuspendLayout();
            // 
            // list
            // 
            _List.Dock = System.Windows.Forms.DockStyle.Fill;
            _List.Font = new System.Drawing.Font("SimSun", 15F);
            _List.FormattingEnabled = true;
            _List.ItemHeight = 20;
            _List.Location = new System.Drawing.Point(0, 0);
            _List.Name = "list";
            _List.Size = new System.Drawing.Size(205, 130);
            _List.TabIndex = 0;
            // 
            // PapersList
            // 
            this.ClientSize = new System.Drawing.Size(205, 130);
            this.Controls.Add(this._List);
            this.Name = "PapersList";
            this.Text = "Paper List";
            this.ResumeLayout(false);
        }
    }
}
